### PR TITLE
Add support for laravel passport 10

### PR DESCRIPTION
**Pull request by lloricode**
docs for [Upgrading To 10.0 From 9.x](https://github.com/laravel/passport/blob/71d1a70a920f991e4f459f4896b9a32fefb3f5d5/UPGRADE.md#upgrading-to-100-from-9x)

### CODE REVIEW

**Comment by ankurk91** [comment]
Passport v10 has not been released yet, i will look into this PR, once it is released.

**Comment by ankurk91** [comment]
@lloricode

Test cases are failing, would you like to fix them?
Feel free to drop support for older version.

**Comment by lloricode** [comment]
> @lloricode
> 
> Test cases are failing, would you like to fix them?
> Feel free to drop support for older version.

yes I will

**Comment by lloricode** [comment]
notice that `laminas/laminas-diactoros` removed in [v9.3.2...v10.0.0](https://github.com/laravel/passport/compare/v9.3.2...v10.0.0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L30)

**Comment by lloricode** [comment]
> Feel free to drop support for older version.

no need to do this, since its depend on what laravel version they use, and all fixes can fetch in different versions

**Comment by lloricode** [comment]
@ankurk91 done passing test

**Pull request merged**
